backend:
  name: github
  repo: Gabriel-Knauder/webshop  # dein GitHub-Repo
  branch: main

media_folder: "assets/images"     # wo Bilder gespeichert werden
public_folder: "/assets/images"   # wo Bilder im Web sind

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - file: "index.md"
        label: "Startseite"
        name: "homepage"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
